name: egg_workspace-env

channels:
  - conda-forge
  - pytorch
  - defaults
  
dependencies:
  - python=3.7
  - pip
  - ipykernel
  - cudatoolkit=11.3
  - pytorch
  - torchvision
  - torchtext 
  - torchaudio
  - pip:
    - -r requirements.txt
